# Generated by Django 4.2 on 2023-04-22 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offer', models.PositiveIntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='car_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=1000)),
                ('km', models.PositiveIntegerField()),
                ('first_registration_date', models.DateField()),
                ('power', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('damage_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('picked_up', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('time_of_advert', models.DateTimeField(blank=True, null=True)),
                ('auctioned', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, to='seller_dashboard.carimage')),
                ('offers', models.ManyToManyField(blank=True, to='seller_dashboard.bidoffer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
