# Generated by Django 4.2 on 2023-04-23 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidoffer',
            options={'ordering': ['date_time']},
        ),
        migrations.AddField(
            model_name='bidoffer',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
