# Generated by Django 4.2 on 2023-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='time_of_advert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(blank=True, to='seller_dashboard.carimage'),
        ),
    ]
