# Generated by Django 4.2 on 2023-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0002_car_price_car_time_of_advert_alter_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='auctioned',
            field=models.BooleanField(default=False),
        ),
    ]
