# Generated by Django 4.2 on 2023-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_dashboard', '0003_car_auctioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('cars', models.ManyToManyField(blank=True, to='seller_dashboard.car')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
