# Generated by Django 4.2 on 2023-04-19 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auction_ended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['start']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_time',
        ),
        migrations.AddField(
            model_name='auction',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
