# Generated by Django 4.2 on 2023-04-19 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_auction_options_remove_auction_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
    ]
