# Generated by Django 4.2 on 2023-04-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0004_car_damage_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.car')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
