# Generated by Django 4.2 on 2023-04-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_bidoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidOffer',
        ),
    ]
