# Generated by Django 4.2 on 2023-04-12 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='car_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=1000)),
                ('km', models.PositiveIntegerField(max_length=1000)),
                ('first_registration_date', models.DateField()),
                ('power', models.CharField(max_length=1000)),
                ('images', models.ManyToManyField(to='car_app.carimage')),
            ],
        ),
    ]
