# Generated by Django 4.2 on 2023-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.PositiveIntegerField(),
        ),
    ]
